version: '3.8'

services:

  python-fakedsmr:
    build: ./fakedsmr
    # environment:
    #   - BROKER_ADDRESS=mosquitto
    # depends_on:
    #   - mosquitto
    restart: unless-stopped
    profiles:
      - fakedsmr

