FROM nodered/node-red:latest

# Install any extra Node-RED packages
RUN npm install node-red-dashboard 

# Copy the package.json file to the container
# COPY package.json /data/

# Copy the flow file to the container
# COPY flows.json /data/flows.json
